#!/bin/bash

SCP="scp"
SSH_PORT=22
USER="name"
HOSTS=("sub1.example.com" "sub2.example.com")
DIR="/var/www/pub/debian"
FILES="*.deb *.dsc *.tar.gz *.buildinfo *.changes"

for ((i = 0; i < ${#HOSTS[@]}; i++)); do
    ${SCP} -P ${SSH_PORT} ${FILES} ${USER}@${HOSTS[${i}]}:${DIR}
done
